### ISSUE TITLE
Publish latest version to npm registry

### ISSUE THREAD

**Issue by hugmanrique** [pmowrer/rollup-plugin-peer-deps-external#15]
The build including the #10 fix has not been published, so I'm still getting the peer dep requirement warning on npm:

```
npm WARN rollup-plugin-peer-deps-external@2.2.0 requires a peer of rollup@^0.x but none is installed. You must install peer dependencies yourself.
```

This would be a good time to automate releases through the new GitHub actions feature.

**Comment by cdfa** [comment]
Any updates on this?

**Comment by pmowrer** [comment]
Hopefully this should be fixed within the week

**Comment by clehene** [comment]
> Hopefully this should be fixed within the week

which week? :)

**Comment by pmowrer** [comment]
> which week? :)

Fair question 😅 As soon as I get publishing rights... Unfortunately not within my control, but should be soon

**Comment by pmowrer** [comment]
This week! 😬
