### ISSUE TITLE
Mismatching Versions Of React

### ISSUE THREAD

**Issue by zwhitchcox** [pmowrer/rollup-plugin-peer-deps-external#18]
I'm using this plugin, and when I try to use react as a peer dependency, it downloads react.

I install with `yarn add --peer react`, and it adds it to my actual `node_modules` folder. So, the only way to get it not to use that version and get a "mismatched versions of React" error is to delete it directly in the `node_modules` directory.

That worked fine, but now, I'm trying to use `@material-ui/core`, and that has its own version of react too, so I am trying to include it as a peer dependency. It is installed in my main project, but my current project is using its own.

I installed it with `yarn add --peer @material-ui/core`, and it gave me the "mismatched versions of react" error, so I deleted `@material-ui/core` from my `node_modules` directory, but now it's saying "cannot find node_modules/@material-ui/core".

Yeah, that's because it's a peer dependency. You're not supposed to find it, you're support to import it externally.

Isn't this what `rollup-plugin-peer-deps-external` is supposed to do? The docs are very sparse, and I can't really tell if I'm using it the proper way or if there is a bug in it.

**Comment by zwhitchcox** [comment]
Ok, I actually figured it out, when I installed @material-ui/core, it installed react again, so I just had to delete if from `node_modules` again.

Surely, this is not the expected behavior though, right? I mean, what does this module actually do, if it doesn't externalize the peer dependencies?

**Comment by zwhitchcox** [comment]
It's still giving me issues, because there are multiple version of @material-ui/core running at the same time, which messes up the colors

**Comment by zwhitchcox** [comment]
I fixed this issue by adding

`declare module "@material-ui/core" `

to my typings.d.ts file

**Comment by fcastillo90** [comment]
> I fixed this issue by adding
> 
> `declare module "@material-ui/core" `
> 
> to my typings.d.ts file

@zwhitchcox Hi! im having the same issues you did, can you post your code or explain how you've managed to resolve it? thanks!

**Comment by pneedham-mdsol** [comment]
Same here as well, although the project I'm working with isn't using Typescript
