### ISSUE TITLE
includeDependencies option description is a bit confusing

### ISSUE THREAD

**Issue by DMXL** [pmowrer/rollup-plugin-peer-deps-external#26]
> Sometimes it's necessary to include a package as a direct dependency instead of a peer dependency. This can happen if your package has a very specific requirement on the dependency and cannot accept another version.

Isn't this describing the scenario where we DON'T want to rely on external dependencies?

**Comment by pmowrer** [comment]
I agree it's confusing. Honestly, I'd rather remove the option since it doesn't align with this plugin's use-case.
